### cpu版本  pip install tensorflow
### g pu版本 pip install tensorflow-gpu

In [27]:
import tensorflow as tf
import numpy as np

In [28]:
tf.__version__

'2.6.2'

In [3]:
# pip install tensorflow-gpu

    100% |████████████████████████████████| 81.2MB 3.9MB/s ta 0:00:0111
^C
Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas as pd

df = pd.DataFrame({"name":["jack"], "age":[20]})

In [5]:
df

name  age
0  jack   20

In [6]:
df.columns

Index(['name', 'age'], dtype='object')

In [7]:
for col in df.columns:
    print(col)

name
age


#### tensor 是什么？是一个矩阵，当作是可以进行g pu加速计算的矩阵

In [14]:
x = [[1.]]
m = tf.matmul(x, x)
print(m)

tf.Tensor([[1.]], shape=(1, 1), dtype=float32)


In [15]:
x = tf.constant([[1, 9],[3, 6]])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [3, 6]], dtype=int32)>

In [19]:
x = tf.add(x, 1)
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4, 12],
       [ 6,  9]], dtype=int32)>

In [21]:
# 转换格式
x.numpy()

array([[ 4, 12],
       [ 6,  9]], dtype=int32)

In [22]:
# 类型转换：int32 转 float32
x = tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4., 12.],
       [ 6.,  9.]], dtype=float32)>

In [24]:
x1 = np.ones([2, 2])
x1
x2 = tf.multiply(x1, 2)
x2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2., 2.],
       [2., 2.]])>